def main.main():
    let t0 = newchan main.main0.t0_chan20, 20;
    spawn main.prod(t0);
    spawn main.prod(t0);
    spawn main.prod(t0);
    spawn main.prod(t0);
    spawn main.prod(t0);
    spawn main.prod(t0);
    spawn main.prod(t0);
    spawn main.prod(t0);
    spawn main.prod(t0);
    spawn main.prod(t0);
    spawn main.prod(t0);
    spawn main.prod(t0);
    spawn main.prod(t0);
    spawn main.prod(t0);
    spawn main.prod(t0);
    spawn main.prod(t0);
    spawn main.prod(t0);
    spawn main.prod(t0);
    spawn main.prod(t0);
    spawn main.prod(t0);
    spawn main.cons(t0);
def main.prod(a):
    call main.prod#1(a);
def main.prod#1(a):
    send a;
    call main.prod#1(a);
def main.cons(a):
    call main.cons#1(a);
def main.cons#1(a):
    recv a;
    call main.cons#1(a);
